fmesolr:
 build: fme_solr/
# volumes:
#  - /home/path_to_index/solr4.10.4/solr:/opt/solr/example/solr
 cap_add:
  - SYS_PTRACE
fmeapache:
 build: fme_apache/
 ports:
  - "80:80"
 links:
  - fmesolr:solr
